@log=http://localhost:3000/auth

post {{log}}/signup
Content-Type: application/json

{
    "username":"deva243",
    "name":"deva",
    "password":"deva@1234",
    "role":"user"
}
###
post {{log}}/signin
Content-Type: application/json

{
    "username":"lenin123",
    "password":"lenin@123"
}